language: node_js
cache:
  directories:
    - ~/.yarn
notifications:
  email: false
node_js:
  - "10"
  - "8"
script:
  - yarn build
after_success:
  - yarn travis-deploy-once "yarn semantic-release"
branches:
  only:
    - master
